### ISSUE TITLE
Can not export colors in 0.32.2

### ISSUE THREAD

**Issue by ink1804** [RedMadRobot/figma-export#160]
I tried to export colors with new version 0.32.2 but an error appears.
`AndroidExport/resource_bundle_accessor.swift:27: Fatal error: unable to find bundle named figma-export_AndroidExport
zsh: trace trap  figma-export colors
`
in version 0.23.4 everything is ok. 
I tried many files, even from yours example and the result is the same.

Any idea whats happened?

**Comment by subdan** [comment]
Hello. I will check it out and get back to you.

**Comment by subdan** [comment]
How did you install FigmaExport: via homebrew or download zip from [Releases](https://github.com/RedMadRobot/figma-export/releases) page?

**Comment by subdan** [comment]
The error says that file `figma-export_AndroidExport.bundle` could not be found. This file contains Stencil templates FigmaExport uses since 0.32.0. If you use Homebrew this file is installed automatically. If you use manual installation from zip file please check that the bundle file located near the `figma-export` binary file.

What is you OS: macOS, Windows or Linux?

**Comment by ink1804** [comment]
@subdan from homebrew, but i had to copy figma-export file into usr/local/bin, because android studio doesn't use default brew path.
Mac os

**Comment by subdan** [comment]
So, you need to copy all the files to fix the issue.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/410293/159873730-7148ff6e-b9d5-4985-ac81-1fed98273e19.png">

**Comment by subdan** [comment]
Also try to add symlink to figma-export file inside usr/local/bin
